name: Update firefox-addons

on:
  schedule:
    - cron: "0 4 * * 1" # every week
  workflow_dispatch:

permissions:
  contents: write

jobs:
  firefox-addons-update:
    name: Update firefox addons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Find flake.nix directory
        id: flake-dir
        run: |
          FLAKE_DIR=$(dirname $(find . -name "flake.nix" -not -path "*/node_modules/*" | head -1))
          echo "dir=$FLAKE_DIR" >> $GITHUB_OUTPUT

      - name: Build firefox-fetch-addons
        working-directory: ${{ steps.flake-dir.outputs.dir }}
        run: nix build .#firefox-addons-fetcher

      - name: Run firefox-fetch-addons
        working-directory: ${{ steps.flake-dir.outputs.dir }}
        run: |
          ./result/bin/firefox-fetch-addons \
            packages/firefox-addons/input.json \
            -o packages/firefox-addons/output.nix

      - name: Commit changes
        run: |
          nix fmt

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

          if ! git diff --cached --quiet; then
            git commit -m "flake: updated firefox-addons [automated]"
            git push
          else
            echo "No changes from updater"
          fi
